server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://192.168.218.134:3306/hotel?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: http://192.168.218.134:9200

logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.onenewcode.esdemo.pojo